sudo: false
language: go
go:
- 1.6
script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go test -v ./...
- go vet
- go test -coverprofile=profile.out -covermode=count
- goveralls -service=travis-ci -coverprofile=profile.out -repotoken $COVERALLS
notifications:
  email: false
