sudo: false
language: go
go:
- 1.6

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
- go get ./...
- go test -v ./...
- $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false
